#! /usr/bin/env bash

# go to DOTFILES folder
DOTFILES=$HOME/.dotfiles
if [ ! -e $DOTFILES ]; then
    git clone --recurse-submodules git@github.com:marco-souza/.dotfiles.git $DOTFILES
fi
cd $DOTFILES

# load stow folders
STOW_FOLDERS=($(ls -l $DOTFILES | awk '/^d/ {print $9}' | tr '\n' ' '))

# Removing stow folders
for folder in $STOW_FOLDERS; do
    echo Removing $folder...
    stow -D $folder
done
echo Done!

# come back to the previous word dir
cd -
